// !!!! DO NOT EDIT !!!, use: make config

#ifndef _CONFIG_H_
#define _CONFIG_H_

// CONFIG_DEBUG is not set
// CONFIG_FIXEDPOINT_MATH is not set
// USE_LCD_CHARGE_PUMP is not set
#define USE_WATCHDOG
#define CONFIG_RTC_IRQ
#define CONFIG_TIMER_4S_IRQ
#define CONFIG_TIMER_20HZ_IRQ
#ifndef CONFIG_BUTTONS_LONG_PRESS_TIME
#define CONFIG_BUTTONS_LONG_PRESS_TIME 6
#endif // CONFIG_BUTTONS_LONG_PRESS_TIME
#ifndef CONFIG_BUTTONS_SHORT_PRESS_TIME
#define CONFIG_BUTTONS_SHORT_PRESS_TIME 1
#endif // CONFIG_BUTTONS_SHORT_PRESS_TIME
#define CONFIG_BATTERY_MONITOR
// CONFIG_BATTERY_DISABLE_FILTER is not set
#define CONFIG_TEMPERATURE_METRIC_ONLY
// CONFIG_STOPWATCH is not set
#define CONFIG_CLOCK
// CONFIG_CLOCK_BLINKCOL is not set
// CONFIG_CLOCK_AMPM is not set
// CONFIG_CLOCK_MONTH_FIRST is not set
// CONFIG_ALARM is not set
#define CONFIG_BATTERY
#define CONFIG_BATTERY_SHOW_VOLTAGE
// CONFIG_ACCELEROMETER is not set
// CONFIG_TEMPERATURE is not set
#define CONFIG_RFBSL
// CONFIG_MUSIC is not set
#define CONFIG_INTERTECHNO
// CONFIG_TIDE is not set

#endif // _CONFIG_H_
